### ISSUE TITLE
Consideration to Push to KiCAD

### ISSUE THREAD

**Issue by ashtonchase** [SchrodingersGat/Battery_Holders_Old.pretty#1]
Hi @SchrodingersGat , 

Have you considered adding this as a KiCAD official repo? I think it would be beneficial. 

Currently, I don't know where battery holders are in the official repos.

Thanks,
Ashton

P.S. I didn't know any other way to get the message to you.

**Comment by SchrodingersGat** [comment]
I'd like to but I don't have the permissions to add new repositories.

**Comment by ashtonchase** [comment]
@CarlPoirier,

Would you consider adding this repo to the Kicad Repos? 

-Ashton
